project:
  type: website
  resources: 
    - "*.pdf"
    - "*.doc"

website:
  title: "Lecture Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: oby.qmd
        text: OBY
      - href: cytology.qmd
        text: Cytology
      - href: cpc.qmd
        text: CPC

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

