project:
  type: website

website:
  title: "Lecture Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: oby.qmd
        text: OBY

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

