project:
  type: website

website:
  title: "Lecture Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: oby.qmd
        text: OBY
      - href: EndometrialCancerSlide.qmd
        text: Lecture slide
      - href: rep.qmd
        text: Cytology slide

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

